services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - RESEND_API_KEY=${RESEND_API_KEY}
    container_name: my-portfolio-app
    ports:
      - "127.0.0.1:3000:3000" 
    restart: unless-stopped
    environment:
      - RESEND_API_KEY=re_GMwq5Zv6_bAn5ziuoXDt6KyRcxVx2Y4TZ